name: "integration-test"
on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:
jobs:
  buildAndTest:
    env:
      PACKED_JS_PATH: 'dist/index.js'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test